### ISSUE TITLE
User Interface & User Experience

### ISSUE THREAD

**Issue by swhp** [NanoDesuTranslations/editor#1]
Since I just create simple UI so how should we design UI & UX for editor site?

**Comment by DerekRS** [comment]
Currently working on this in a fork: https://github.com/DerekRS/editor

**Comment by swhp** [comment]
I think we still need to experiment with the UX, let's assume people who will use this website is not know how to create a new series or page. So, make easy to use UI is a must and add some tooltip or FAQ page it will be great

**Comment by swhp** [comment]
fix on release version [2.0.0](https://github.com/NanoDesuTranslations/editor/releases/tag/2.0.0)
