### ISSUE TITLE
Confirmation dialogs for "irreversible" actions

### ISSUE THREAD

**Issue by DerekRS** [NanoDesuTranslations/editor#10]
From https://github.com/NanoDesuTranslations/generator/issues/12: 
> right now when you delete a page in an editor it just does it without any warning. Add a dialogue to prevent accidental deletions. 

In addition, other serious actions like deleting a series need a confirmation.

Implement with a modal dialog in some re-usable form.

**Comment by swhp** [comment]
For your information, we can use third party library for this
* [alertifyjs](http://alertifyjs.com/)
* [ng-alertify](https://www.npmjs.com/package/ng-alertify) 
* [ng messages](https://docs.angularjs.org/api/ngMessages)

**Comment by swhp** [comment]
I tried to using [alertifyjs.org](https://alertifyjs.org) since it have angularjs way. So what do you think?
